export const moonlitDojoCartridge = {
  id: 'moonlit-dojo',
  title: 'Moonlit Draw',
  subtitle: 'stillness before the strike',
  posterUrl: 'https://yinxinghuan.github.io/games/posters/moonlit-draw.png',
  bestKey: 'moonlit-draw.best',
  themeClass: 'theme-moonlit-dojo',
  copy: {
    guide: 'Tap the instant the moon flashes',
    draw: 'STRIKE!',
    wait: 'HOLD STILL...',
    foul: 'BROKE FORM!',
    lose: 'TOO SLOW',
    versus: 'DUEL',
    overTag: 'Lesson over',
    overTitle: 'You missed the opening',
    killerPrefix: 'against',
    fallbackKiller: 'The Silent Blade',
    winsLabel: 'Duels won',
    bestLabel: 'Best strike',
    again: 'Strike again',
    ranking: 'View ranking',
    leaderboardTitle: 'Moon Ladder',
    leaderboardSubtitle: 'Most clean strikes',
    leaderboardImagePrompt: 'Two low-poly voxel duelists in a moonlit dojo garden, lanterns glowing, hands waiting for a lightning-fast strike.',
    beatMessage: '{sender_name} passed your mark - {score} clean strikes on Moonlit Draw.',
  },
  opponents: [
    'First Lantern', 'River Reed', 'Soft Step', 'Iron Sleeve', 'Crane Shadow',
    'Rain Listener', 'Temple Bell', 'Mirror Guard', 'Paper Tiger', 'White Fan',
    'Midnight Tutor', 'The Silent Blade', 'The Moon Itself',
  ],
  fighters: {
    playerKeys: ['student', 'worker', 'teen', 'fitWoman'],
    opponentKeys: ['securityGuard', 'cop', 'biker', 'goth', 'nurse', 'firefighter', 'businessman'],
  },
  tuning: {
    setMin: 1.05,
    setMax: 3.25,
    leadIn: 0.42,
    opponentReactionStart: 0.56,
    opponentReactionFloor: 0.16,
    opponentReactionStep: 0.033,
    opponentJitter: 0.026,
  },
  colors: {
    css: {
      ink: '#eff7ff',
      inkSoft: '#a7c2d8',
      gold: '#b8f0ff',
      goldDeep: '#58a8d8',
      rust: '#ff9d7a',
      red: '#ff6d85',
      wood1: '#0c1624',
      wood2: '#172235',
      amber: '#9dd9ff',
      pageTop: '#07101d',
      pageMid: '#24345a',
      pageBottom: '#9cc7dd',
    },
    skyTop: 0x07101d,
    skyMid: 0x24345a,
    skyBottom: 0x9cc7dd,
    skyGlow: 0xe7fbff,
    fog: 0x5d7f9f,
    sun: 0xe7fbff,
    hemiSky: 0xd8f2ff,
    hemiGround: 0x172235,
    keyLight: 0xd7f3ff,
    rimLight: 0xffc0a0,
    ground: 0x263447,
    road: 0x1b2534,
    cactus: 0x405f6f,
    town: 0x1d2a39,
    townTrim: 0x324963,
    motes: 0xc8f3ff,
    muzzle: 0xc7f6ff,
    muzzleCore: 0xffffff,
    blade: 0xe7fbff,
  },
  world: {
    props: 'dojo',
    backdrop: 'dojo-gate',
    duelSeparation: 1.24,
  },
  action: {
    prop: 'blade',
    effect: 'slash',
    sound: 'blade',
    reach: 1.1,
  },
};
