export const westernCartridge = {
  id: 'western',
  title: 'Quick Draw',
  subtitle: 'fastest hand in the feed',
  posterUrl: 'https://yinxinghuan.github.io/games/posters/quick-draw.png',
  bestKey: 'quick-draw.best',
  themeClass: 'theme-western',
  copy: {
    guide: 'Tap the instant it says DRAW',
    draw: 'DRAW!',
    wait: 'WAIT FOR IT...',
    foul: 'TOO EARLY!',
    lose: 'OUT-DRAWN',
    versus: 'VS',
    overTag: 'Six feet under',
    overTitle: 'You got out-drawn',
    killerPrefix: 'by',
    fallbackKiller: 'The Drifter',
    winsLabel: 'Duels won',
    bestLabel: 'Best draw',
    again: 'Draw again',
    ranking: 'View ranking',
    leaderboardTitle: 'Most Wanted',
    leaderboardSubtitle: 'Most duels won',
    leaderboardImagePrompt: 'Two low-poly voxel gunslingers in a dusty Wild-West standoff at golden dusk, hands hovering over holsters.',
    beatMessage: '{sender_name} out-drew your record - {score} duels won on Quick Draw.',
  },
  opponents: [
    'The Greenhorn', 'Dusty Pete', 'The Drifter', 'One-Eye Jack', 'Calamity Sue',
    'Three-Finger Lou', 'Dead-Eye Dan', 'Black Bart', 'Rattlesnake Kate', 'El Diablo',
    'The Undertaker', 'The Marshal', 'The Reaper',
  ],
  fighters: {
    playerKeys: null,
    opponentKeys: null,
  },
  tuning: {
    setMin: 1.2,
    setMax: 3.6,
    leadIn: 0.45,
    opponentReactionStart: 0.54,
    opponentReactionFloor: 0.17,
    opponentReactionStep: 0.034,
    opponentJitter: 0.03,
  },
  colors: {
    css: {
      ink: '#fbecd2',
      inkSoft: '#c9a980',
      gold: '#ffcb52',
      goldDeep: '#e08a2a',
      rust: '#e0492f',
      red: '#ff5a3c',
      wood1: '#241019',
      wood2: '#3a1c1e',
      amber: '#caa05a',
      pageTop: '#2a2148',
      pageMid: '#b5547a',
      pageBottom: '#f2a850',
    },
    skyTop: 0x2a2148,
    skyMid: 0xb5547a,
    skyBottom: 0xf2a850,
    skyGlow: 0xffd27a,
    fog: 0xd9956a,
    sun: 0xffe39a,
    hemiSky: 0xffe0b0,
    hemiGround: 0x4a2f3a,
    keyLight: 0xffd9a0,
    rimLight: 0x8fb0ff,
    ground: 0xcf9b63,
    road: 0xb07f4e,
    cactus: 0x4f7a3a,
    town: 0x6e4a3a,
    townTrim: 0x553828,
    motes: 0xffe6c0,
    muzzle: 0xffd06a,
    muzzleCore: 0xffe79a,
    blade: 0xffe79a,
  },
  world: {
    props: 'western',
    backdrop: 'western-town',
    duelSeparation: 1.7,
  },
  action: {
    prop: 'revolver',
    effect: 'muzzle',
    sound: 'shot',
    reach: 0.4,
  },
};
